name: Map GitHub Actor
description: |-
  Maps the user that triggered the action to a list of known mappings - be it Slack ids, email addresses, etc.

branding:
  icon: activity
  color: red

inputs:
  actor-map:
    description: The actor mapping JSON file
    required: true
  default-mapping:
    description: The default mapping in case the actor is not found in the map
    required: true

outputs:
  actor-mapping:
    description: The corresponding value mapped to the actor

runs:
  using: node12
  main: dist/index.js
