volumes:
  node_modules:

services:
  dev:
    image: icalia-actions/map-actor-to-slack:development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}
    working_dir: /workspaces/map-actor-to-slack
    entrypoint: /workspaces/map-actor-to-slack/bin/dev-entrypoint
    volumes:
      - .:/workspaces/map-actor-to-slack
      - node_modules:/workspaces/map-actor-to-slack/node_modules

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
