volumes:
  vscode_extensions:
  vscode_insiders_extensions:

services:
  dev:
    volumes:
      - .:/workspaces/map-actor-to-slack
      - node_modules:/workspaces/map-actor-to-slack/node_modules
      - vscode_extensions:/home/${USER:-you}/.vscode-server/extensions
      - vscode_insiders_extensions:/home/${USER:-you}/.vscode-server-insiders/extensions

    # The command we want to execute by default when running the container
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined

    command: vscode-wait # Éste comando está definido en `bin/dev-entrypoint`

    environment:
      GIT_EDITOR: code
